#! /bin/sh

# dnf install -y glib2-devel

set -e

if ! hash gresource 2>/dev/null; then
  echo "Library glib2-devel not found. dnf install -y glib2-devel"
  exit 1
fi

if [ -n "$1" ]
then
  workdir=$(mktemp -d)
  image="$1"
else
  workdir="/usr/share/gnome-shell/wallpaper"
  image="$workdir/wallpaper-gnome.png"
fi

if [ ! -f $image ]
then
  echo "File not found: \"$image\" "
  exit 1
fi

echo "Updating wallpaper..."

mkdir -p $workdir/theme

echo '<?xml version="1.0" encoding="UTF-8"?>
<gresources>
  <gresource prefix="/org/gnome/shell/theme">' > $workdir/gnome-shell-theme.gresource.xml

gst=/usr/share/gnome-shell/gnome-shell-theme.gresource
for r in `gresource list $gst`; do
  gfile="${r#\/org\/gnome\/shell\/theme/}";
  mkdir -p "$(dirname $workdir/theme/$gfile)"

  if [ "$gfile" != "wallpaper-gdm.png" ]; then
    gresource extract $gst $r >$workdir/theme/$gfile
    echo "    <file>$gfile</file>" >> $workdir/gnome-shell-theme.gresource.xml
  fi
done

echo "    <file>wallpaper-gdm.png</file>" >> $workdir/gnome-shell-theme.gresource.xml
cp -f $image $workdir/theme/wallpaper-gdm.png

echo '  </gresource>
</gresources>' >> $workdir/gnome-shell-theme.gresource.xml

sed -i -e 's/background: #2e3436 url(resource:\/\/\/org\/gnome\/shell\/theme\/noise-texture.png);/background: #2e3436 url(resource:\/\/\/org\/gnome\/shell\/theme\/wallpaper-gdm.png);background-size: cover;/g' $workdir/theme/gnome-shell.css

cd $workdir/theme
glib-compile-resources $workdir/gnome-shell-theme.gresource.xml

if ! grep -q "wallpaper-gdm.png" /usr/share/gnome-shell/gnome-shell-theme.gresource; then
  cp -f /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.backup
  echo "Backup"
fi

cp -f $workdir/gnome-shell-theme.gresource /usr/share/gnome-shell/

rm -rf $workdir/theme
rm -f $workdir/gnome-shell-theme.gresource.xml
rm -f $workdir/gnome-shell-theme.gresource

echo "Done!"
